// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBqg9uVgZ5NVddAx6LjbmNGJb9vV7LzI',
    appId: '1:987949205496:web:d6f8f720d80a804238780d',
    messagingSenderId: '987949205496',
    projectId: 'vt-hacks-submission',
    authDomain: 'vt-hacks-submission.firebaseapp.com',
    storageBucket: 'vt-hacks-submission.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZC9UFABpVg0YVcoMuG17v4TmO3BPb2I',
    appId: '1:987949205496:android:5fcf7b6d8c915c1438780d',
    messagingSenderId: '987949205496',
    projectId: 'vt-hacks-submission',
    storageBucket: 'vt-hacks-submission.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxaGdlpitlxC2_sonk3Xi7r4fKE_2CQXk',
    appId: '1:987949205496:ios:178438be314d732638780d',
    messagingSenderId: '987949205496',
    projectId: 'vt-hacks-submission',
    storageBucket: 'vt-hacks-submission.appspot.com',
    iosClientId:
        '987949205496-kmf5mkluf1li4h5suqdte5amrovlrkhr.apps.googleusercontent.com',
    iosBundleId: 'com.infofriend.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxaGdlpitlxC2_sonk3Xi7r4fKE_2CQXk',
    appId: '1:987949205496:ios:178438be314d732638780d',
    messagingSenderId: '987949205496',
    projectId: 'vt-hacks-submission',
    storageBucket: 'vt-hacks-submission.appspot.com',
    iosClientId:
        '987949205496-kmf5mkluf1li4h5suqdte5amrovlrkhr.apps.googleusercontent.com',
    iosBundleId: 'com.infofriend.app',
  );
}
